services:
  discord-bot:
    image: superknacky/discord-bot:latest
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=token
    ports:
      - "5001:5001"
    restart: unless-stopped
