services:
  discord-bot:
    image: warden696/node-changedetection-api-bot:22.3.0-alpine
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=token
    ports:
      - "5001:5001"
    restart: unless-stopped
